### ISSUE TITLE
Peer dependencies for msteams-ui-components-react

### ISSUE THREAD

**Issue by wictorwilen** [OfficeDev/msteams-ui-components#148]
When installing `msteams-ui-components-react"` with `npm` I get a lot of peer dependency warnings and I have to manually install those (as `npm install` does not install peer dependencies automatically anymore).

Shouldn't they be moved to *normal* dependencies?

**Comment by MattSFT** [comment]
Typestyle should be our only peer dependency. We listed it as such because you might want to use typestyle in your entire project and there's no need to have two different versions of it installed.

**Comment by wictorwilen** [comment]
Check, but React is also in the peer depency list

**Comment by MattSFT** [comment]
I forgot react is on there also. Same reasoning for react. Especially since most projects that use this library will use react as well we don't want to force users to use our react version and we don't want to have users use two versions of react in their project. As long as the project you use this library in has a sufficient version of react installed, everything should be fine.

**Comment by wictorwilen** [comment]
Makes total sense! Thanks.
