### ISSUE TITLE
Semantic Colors

### ISSUE THREAD

**Issue by benpolinsky** [OfficeDev/msteams-ui-components#155]
Any chance of a `Colors` object that lets developers understand a property's color by context/semantics, rather than by color name?  Because each theme has a different selection of colors, it's difficult to create stylesheets that easily switch between themes. I currently have a very large case statement that assigns the proper colors to each variable I can then utilize.

For example, as opposed to `Colors.dark.black`, we'd have `Colors.dark.mainBackground`
As opposed to `Colors.contrast.yellow` we'd have `Colors.contrast.mainFont` or something similar.

That way, we can declare our styles once, and let a specific theme string do the heavy lifting:

<pre>
.someSelector: Colors[<b>theme</b>]['mainBackground'];
</pre>

Thanks!

**Comment by MattSFT** [comment]
Hey Ben,

Thanks for the feedback! I think we originally had this sort of paradigm in the library a long time ago (before it was public). We then fell back onto having a color palette object and putting the semantic bit into the actual components.

We did this because we noticed that our designers and designers we worked with before have a color palette and choose the colors from it as they see fit... so generally the colors do have a semantic use but there are exceptions and we didn't want to have things like:
Colors.dark.mainBackground
Colors.dark.mainBackgroundOnlyForPanels

This would get even more annoying if design merges these exceptional cases together and now we have to mainBackground properties and we have to deprecate some, etc...

So for us the color object is the palette that we use throughout the controls... design is free to change the color palette or the colors used in any control independently and we can easily capture that change.

If you want to take a look at how you can get the main background or font colors from a semantic source you could grab them from [here](https://github.com/OfficeDev/msteams-ui-components/blob/master/msteams-ui-styles-core/src/components/surface.ts)

The code might be a little complicated to understand and maybe we can refactor it to be used better... but it is a good starting point. (Our switch statement based on theme lives in the chooseStyle function which we get from the context; the context knows the theme). (ref for [context](https://github.com/OfficeDev/msteams-ui-components/blob/master/msteams-ui-styles-core/src/context.ts))

I hope that makes sense.

**Comment by benpolinsky** [comment]
Hi,

Definitely makes sense!  I think I'm currently doing something very similar, but I'll check these links out for sure.

Much appreciated.
